remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "contrast"
title: Yun-Chien Lu
include: ["_pages"]
repository: "luyunchien/luyunchien.github.io"
atom_feed:
  hide: true