remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "contrast"
title: Yun-Chien Lu
include: ["_pages"]
repository: "luyunchien/luyunchien.github.io"
atom_feed:
  hide: true
author:
  name: "Yun-Chien Lu"
  bio: "Computer Science Graduate"
  avatar: "assets/img/avatar.jpg"
  location: "United Kingdom"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:luyunchien@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yun-chien-lu/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/luyunchien"
footer:
  links:
    - label: "Page Source"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/luyunchien/luyunchien.github.io"
locale: "en"